USE QL_ChuoiNhaThuoc_CN_HN;
GO
CREATE LOGIN Login_DuocSi_HN WITH PASSWORD = '123456';
CREATE USER User_DuocSi_HN FOR LOGIN Login_DuocSi_HN;
GO

CREATE ROLE Role_DuocSi;
GO

GRANT SELECT, INSERT ON HoaDon TO Role_DuocSi;
GRANT SELECT, INSERT ON ChiTietHoaDon TO Role_DuocSi;
DENY UPDATE, DELETE ON HoaDon TO Role_DuocSi;
DENY UPDATE, DELETE ON ChiTietHoaDon TO Role_DuocSi;

GRANT SELECT, UPDATE ON TonKho TO Role_DuocSi;
GRANT SELECT, UPDATE ON KhachHang TO Role_DuocSi;

GRANT SELECT ON Thuoc TO Role_DuocSi;
GRANT SELECT ON NhomThuoc TO Role_DuocSi;
GRANT SELECT ON HoatChat TO Role_DuocSi;
GRANT SELECT ON BacSi TO Role_DuocSi;

DENY SELECT, INSERT, UPDATE, DELETE ON NhanVien TO Role_DuocSi;
DENY SELECT, INSERT, UPDATE, DELETE ON PhieuNhapKho TO Role_DuocSi;
DENY SELECT, INSERT, UPDATE, DELETE ON ChiTietNhapKho TO Role_DuocSi;
DENY SELECT, INSERT, UPDATE, DELETE ON NhaCungCap TO Role_DuocSi;

ALTER ROLE Role_DuocSi ADD MEMBER User_DuocSi_HN;
GO