USE QL_ChuoiNhaThuoc_CN_HN;
GO

CREATE LOGIN Login_ThuKho_HN WITH PASSWORD = '123456';
CREATE USER User_ThuKho_HN FOR LOGIN Login_ThuKho_HN;
GO

CREATE ROLE Role_ThuKho;
GO

GRANT SELECT, INSERT, UPDATE ON PhieuNhapKho TO Role_ThuKho;
GRANT SELECT, INSERT, UPDATE ON ChiTietNhapKho TO Role_ThuKho;
GRANT SELECT, INSERT, UPDATE ON LoThuoc TO Role_ThuKho;
GRANT SELECT, INSERT, UPDATE ON TonKho TO Role_ThuKho;

GRANT SELECT ON Thuoc TO Role_ThuKho;
GRANT SELECT ON NhomThuoc TO Role_ThuKho;
GRANT SELECT ON NhaCungCap TO Role_ThuKho;
GRANT SELECT ON ChiNhanh TO Role_ThuKho;

DENY SELECT, INSERT, UPDATE, DELETE ON HoaDon TO Role_ThuKho;
DENY SELECT, INSERT, UPDATE, DELETE ON ChiTietHoaDon TO Role_ThuKho;
DENY SELECT, INSERT, UPDATE, DELETE ON NhanVien TO Role_ThuKho;
DENY SELECT, INSERT, UPDATE, DELETE ON KhachHang TO Role_ThuKho;
DENY SELECT, INSERT, UPDATE, DELETE ON BacSi TO Role_ThuKho;

ALTER ROLE Role_ThuKho ADD MEMBER User_ThuKho_HN;
GO